apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jamaica-parish-explorer
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: jamaica.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jamaica-parish-explorer
                port:
                  number: 80

